kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: kst123/obs-ndi
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - latest
